In [ ]:
# 20250225 첫 코랩 수업~~! (그치만 전체로는 17번째라는 . . . )

In [3]:
with open('test.txt','w') as f :
  data = f.write('반가워요')  # 저장이 가능하다. 저장경로는 /content/sample_data
with open('./drive/MyDrive/ReadMe.md','w') as f :   # 저장경로를 지정해줬다 !
  data = f.write('*반가워요')
  print("저장되었습니다.")

In [2]:
with open('./drive/MyDrive/ReadMe.md','w') as f :   # 저장경로를 지정해줬다 !
  data = f.write('*반가워요')
  print("저장되었습니다.")

저장되었습니다.


# 넘파이(numpy)

- ndim : 축의 개수
- shape : 배열의 차원정보
- size : 배열 안에 있는 원소의 총 개수
- dtype : 배열 원소의 자료형

## 1차원과 속성들

In [7]:
# pip install numpy  : 설치를 하지 않았지만 이미 품고 있구만~
import numpy as np
narry = np.array(range(5))
print(narry)  # 넘파이식의 어레이에는 콤마가 없다 (리스트가 아님)

[0 1 2 3 4]


In [ ]:
# Shift + delete 하면 줄 전체를 통째로 날림~!

In [19]:
import numpy as np
narry = np.array(range(5))
print(narry,type(narry))
print(narry.ndim)
print(narry.shape)  # 그냥 5임
print(narry.size)
print(narry.dtype)  # 64bit?
print(narry[3])     #  슬라이싱 하는 것 ~!
print(narry[2:4])   #  <= x < (끝은 미만이라는 것을 기억해!)

[0 1 2 3 4] <class 'numpy.ndarray'>
1
(5,)
5
int64
3
[2 3]


In [20]:
narr1 = np.array([1,2,3,4])   # int64
narr2 = np.array([1,2,'a','b'])
# narr3 = np.array([1,2,'a','b'],dtype='int') # 숫자가 있지만 문자가 들어가면 전부 문자처리 해벌임 !!
print(narr1)
print(narr2)
# print(narr3)

[1 2 3 4]
['1' '2' 'a' 'b']


In [21]:
narr1 = np.array([1,2,3,4])
narr2 = np.array([1,2,'a','b'])
narr3 = np.array([1,2,3,4],dtype='str')
print(narr1,narr1.dtype)
print(narr2,narr2.dtype)
print(narr3,narr3.dtype)

[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [31]:
narr4 = np.zeros(10)
print(narr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [29]:
narr4 = np.zeros(10,dtype='int64')  # 0으로 채운다. 배열을 초기화할 때 !!
print(narr4,type(narr4))  # .이 사라졌다!!

[0 0 0 0 0 0 0 0 0 0] <class 'numpy.ndarray'>


In [64]:
# cf)
apt = np.full((10,2),'□')
print(apt, '🌲🚶🌳🐈🌴')

[['□' '□']
 ['□' '□']
 ['□' '□']
 ['□' '□']
 ['□' '□']
 ['□' '□']
 ['□' '□']
 ['□' '□']
 ['□' '□']
 ['□' '□']] 🌲🚶🌳🐈🌴


In [105]:
narr4 = np.zeros((2,2),dtype='int64')  # (2,2)를 넣어주면 모양을 넣어준 것과 같다!
narr5 = np.ones((2,2))    # you still my No.1 ~ : float은 정확한 값을 주지는 못한다 . . . .
narr6 = np.full((3,3),3)  # 배열 안을 3으로 덮어쓰겠다.
narr7 = np.full((3,3),'number')
narr8 = np.eye(3)
narr9 = np.linspace(0,100,5)  # 0에서 "100을 포함한 !!!" 5개!!
# cf)
narr9n = np.linspace(0,100,5,endpoint=False,dtype='int64')
narr10 = np.arange(0,100,25) # arange는 끝자리가 포함되지 않음 !!!!
print("narr4 : ",narr4,narr4.ndim,narr4.dtype,narr4.shape,narr4.size,type(narr4),"\n")  # 2 차 원 의 배 열
print("narr5 : ",narr5,narr5.ndim,narr5.dtype,narr5.shape,narr5.size,type(narr5),"\n")
print("narr6 : ",narr6,narr6.ndim,narr6.dtype,narr6.shape,narr6.size,type(narr6),"\n")
print("narr7 : ",narr7,narr7.ndim,narr7.dtype,narr7.shape,narr7.size,type(narr7),"\n") # little 기반 / bigindian 기반 . .(ft. 걸리버여행기)
print("narr8 : ",narr8,narr8.ndim,narr8.dtype,narr8.shape,narr8.size,type(narr8),"\n")
print("narr9 : ",narr9,narr9.ndim,narr9.dtype,narr9.shape,narr9.size,type(narr9),"\n")
print("narr9n : ",narr9n,narr9n.ndim,narr9n.dtype,narr9n.shape,narr9n.size,type(narr9n),"\n")
print("narr10 : ",narr10,narr10.ndim,narr10.dtype,narr10.shape,narr10.size,type(narr10))

narr4 :  [[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'> 

narr5 :  [[1. 1.]
 [1. 1.]] 2 float64 (2, 2) 4 <class 'numpy.ndarray'> 

narr6 :  [[3 3 3]
 [3 3 3]
 [3 3 3]] 2 int64 (3, 3) 9 <class 'numpy.ndarray'> 

narr7 :  [['number' 'number' 'number']
 ['number' 'number' 'number']
 ['number' 'number' 'number']] 2 <U6 (3, 3) 9 <class 'numpy.ndarray'> 

narr8 :  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 2 float64 (3, 3) 9 <class 'numpy.ndarray'> 

narr9 :  [  0.  25.  50.  75. 100.] 1 float64 (5,) 5 <class 'numpy.ndarray'> 

narr9n :  [ 0 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'> 

narr10 :  [ 0 25 50 75] 1 int64 (4,) 4 <class 'numpy.ndarray'>


## 2차원 배열

In [51]:
print(list(range(2,10)))
print(np.arange(2,10))  # list로 감싸지 않아도 바로 생성됨!
range(10)
np.arange(10)

[2, 3, 4, 5, 6, 7, 8, 9]
[2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr1 = np.array([[0,0],[0,0]])
print(arr1,arr1.ndim,arr1.dtype,arr1.shape,arr1.size, type(arr1))  # 배열 안의 배열 . . . 상자 속의 상자 ... 슈뢰딩거의 고양이 ...

[[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>


In [74]:
arr2 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr3 = np.arange(1,10).reshape(3,3)   # arr2와 구성은 똑같다 !
arr4 = np.arange(1,11).reshape(2,5)
arr5 = np.arange(1,11).reshape(5,2)
arr6 = np.arange(1,28).reshape(3,3,3)
print('차원:' ,arr2.ndim, '데이터타입:' ,arr2.dtype, '형태:' ,arr2.shape, ' / 크기:', arr2.size, type(arr2),'\n',arr2)
print('차원:' ,arr3.ndim, '데이터타입:' ,arr3.dtype, '형태:' ,arr3.shape, ' / 크기:', arr3.size, type(arr3),'\n',arr3)
print('차원:' ,arr4.ndim, '데이터타입:' ,arr4.dtype, '형태:' ,arr4.shape, ' / 크기:', arr4.size, type(arr4),'\n',arr4)
print('차원:' ,arr5.ndim, '데이터타입:' ,arr5.dtype, '형태:' ,arr5.shape, ' / 크기:', arr5.size, type(arr5),'\n',arr5)
print('차원:' ,arr6.ndim, '데이터타입:' ,arr6.dtype, '형태:' ,arr6.shape, ' / 크기:', arr6.size, type(arr6),'\n',arr6)

차원: 2 데이터타입: int64 형태: (3, 3)  / 크기: 9 <class 'numpy.ndarray'> 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
차원: 2 데이터타입: int64 형태: (3, 3)  / 크기: 9 <class 'numpy.ndarray'> 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
차원: 2 데이터타입: int64 형태: (2, 5)  / 크기: 10 <class 'numpy.ndarray'> 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
차원: 2 데이터타입: int64 형태: (5, 2)  / 크기: 10 <class 'numpy.ndarray'> 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
차원: 3 데이터타입: int64 형태: (3, 3, 3)  / 크기: 27 <class 'numpy.ndarray'> 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [99]:
# 간단한 테스트 !!
test1 = np.arange(1,22).reshape(3,7)
test2 = np.arange(1,8).reshape(7,1)
test3 = np.arange(1,11).reshape(5,2)
test4 = np.arange(1,22).reshape(3,7)
test5 = np.array(([1],[2],[3],[0],[4],[5],[6],[0],[7],[8],[9],[0],[10],[11],[12]),dtype='int').reshape(15,1)
test6= np.arange(1,13).reshape(4,3,1)  # test5 해설 !!!!!  : 전체 개수 3개가 4단위로 1개씩 !!!!
print(test1,end='\n=========================\n')
print(test2,end='\n=========================\n')
print(test3,end='\n=========================\n')
print(test4,end='\n=========================\n')
print(test5,end='\n=========================\n')
print(test6)  # arange를 3차원으로 표현한 것임 !!!!! 크아아아악

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[ 1]
 [ 2]
 [ 3]
 [ 0]
 [ 4]
 [ 5]
 [ 6]
 [ 0]
 [ 7]
 [ 8]
 [ 9]
 [ 0]
 [10]
 [11]
 [12]]
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [108]:
test1[1][2:5]   # 슬라이싱을 할 수 있다 !  : 필요한 값만 가져올 수 있다!

array([10, 11, 12])

In [109]:
test4

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [144]:
print(test4[0:3,3:8])    # 슬라이싱 두 번 ~  : 처음 슬라이싱은 전체 배열에서 몇 행을 선택할 것인지, 두 번째 슬라이싱은 몇 열을 선택할 것인지!! )
print(test4[1:3,4:6])

[[ 4  5  6  7]
 [11 12 13 14]
 [18 19 20 21]]
[[12 13]
 [19 20]]


In [143]:
print([test4>12])      # 조건이 맞을 때 True
print([test4%2==0])
print(test4[test4>12]) # 조건에 맞는 항을 출력하라
print(test4[test4%2==0])

[array([[False, False, False, False, False, False, False],
       [False, False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])]
[array([[False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True, False]])]
[13 14 15 16 17 18 19 20 21]
[ 2  4  6  8 10 12 14 16 18 20]


In [148]:
# np 배열 연산 // shape가 같을 경우 원소별 연산이 가능
np1 = np.array([6,7,8,9,10])
np2 = np.array([1,2,3,4,5])
print("덧셈 : ", np1 + np2)
print("뺄셈 : ", np1 - np2)
print("곱셈 : ", np1 * np2)
print("나눗셈 : ", np1 / np2)
print("거듭제곱 : ", np1 ** np2)

덧셈 :  [ 7  9 11 13 15]
뺄셈 :  [5 5 5 5 5]
곱셈 :  [ 6 14 24 36 50]
나눗셈 :  [6.         3.5        2.66666667 2.25       2.        ]
거듭제곱 :  [     6     49    512   6561 100000]


In [146]:
# np 배열 연산 참고
np1 = np.array([1,2,3,4,5])
np2 = np.array([6,7,8,9,10])
print("덧셈 : ", np1 + np2)
print("뺄셈 : ", np1 - np2)
print("곱셈 : ", np1 * np2)
print("나눗셈 : ", np1 / np2)
print("거듭제곱 : ", np1 ** np2)

덧셈 :  [ 7  9 11 13 15]
뺄셈 :  [-5 -5 -5 -5 -5]
곱셈 :  [ 6 14 24 36 50]
나눗셈 :  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
거듭제곱 :  [      1     128    6561  262144 9765625]


In [150]:
# 브로드캐스팅
np3 = np1 + 10
print(np3)

[16 17 18 19 20]


In [165]:
br1 = np.arange(1,10).reshape(3,3)
br2 = np.array([11,22,33]) #.reshape(3,1)   주석처리했을 때와 안했을 때 어떤 점이 차이 나는지 잘 알아두자 !
print(br1)
print(br2)
# 스칼라와 연산
print("=+=+=+=+=+=+=+=스칼라와 연산=+=+=+=+=+=+=+=")
print(br1)
print(br1+3)
print(br1*2)
# 2D 와 1D의 연산
print("=+=+=+=+=+=+=+=2D와 1D의 연산=+=+=+=+=+=+=+=")
print(br1+br2)
print(br1*br2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[11 22 33]
=+=+=+=+=+=+=+=스칼라와 연산=+=+=+=+=+=+=+=
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
=+=+=+=+=+=+=+=2D와 1D의 연산=+=+=+=+=+=+=+=
[[12 24 36]
 [15 27 39]
 [18 30 42]]
[[ 11  44  99]
 [ 44 110 198]
 [ 77 176 297]]


In [169]:
# flatten 처리
ff = np.arange(1,10).reshape(3,3)
print(ff)
print(ff.reshape(9))   # 굳이 1, 9 할 필요 없음~
print(ff.flatten())   # 일자로 쫙 펴줌!!

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
