In [ ]:
# 새 책 !!!!! 한번에 끝내는~ p 124!!! 갸아아악 그치만 아직 20250228임~

# 판다스(pandas) 심화

In [2]:
import numpy as np
import pandas as pd
print("DataFrame: ")
data = {
        'col1':[2,1,9,8,7,4],
        'col2':['A','A','B', np.nan,'D','C'],
        'col3':[0,1,9,4,2,3]
       }
index = [1,3,2,5,0,4]
df = pd.DataFrame(data,index=index)
df

DataFrame: 


col1 col2  col3
1     2    A     0
3     1    A     1
2     9    B     9
5     8  NaN     4
0     7    D     2
4     4    C     3

In [4]:
# index axis=0(행)을 축으로 정렬
df = df.sort_index(axis=0)  # 꼭 업데이트(스스로에 대입) 해줄 것~!
df

col1 col2  col3
0     7    D     2
1     2    A     0
2     9    B     9
3     1    A     1
4     4    C     3
5     8  NaN     4

In [5]:
# index axis=1(열) 을 축으로 정렬, 내림차순(False)
df = df.sort_index(axis=1, ascending=False)
df

col3 col2  col1
0     2    D     7
1     0    A     2
2     9    B     9
3     1    A     1
4     3    C     4
5     4  NaN     8

In [6]:
# sort_value
sorted_df1 = df.sort_values('col1',ascending=True)  # col1에 대하여 value를 정리하라~
sorted_df1

col3 col2  col1
3     1    A     1
1     0    A     2
4     3    C     4
0     2    D     7
5     4  NaN     8
2     9    B     9

In [8]:
# sort_value 2
sorted_df2 = df.sort_values(['col2','col1'],ascending=[True,False])
sorted_df2   # 같은 col2의 A 안에서 col1의 2가 우선된다 !!

col3 col2  col1
1     0    A     2
3     1    A     1
2     9    B     9
4     3    C     4
0     2    D     7
5     4  NaN     8

In [ ]:
# p88 random number 발생 !!

In [9]:
x = np.random.randint(1,5,size=(10,5))  # 5는 포함되지 않았다!
x

array([[3, 1, 3, 4, 4],
       [3, 1, 4, 1, 1],
       [2, 1, 4, 2, 2],
       [2, 3, 4, 4, 1],
       [4, 1, 1, 4, 3],
       [4, 1, 1, 2, 3],
       [3, 3, 3, 2, 4],
       [2, 3, 4, 4, 1],
       [3, 3, 2, 3, 3],
       [2, 2, 1, 3, 4]], dtype=int32)

In [10]:
x = np.random.rand(10,5)
x

array([[0.97284877, 0.39166695, 0.9044524 , 0.26244709, 0.40727637],
       [0.14131516, 0.90312825, 0.37225506, 0.88513995, 0.98342891],
       [0.27293398, 0.21887321, 0.96876073, 0.82875423, 0.69380651],
       [0.03628662, 0.39956   , 0.59064598, 0.97399987, 0.47847836],
       [0.56970588, 0.06894969, 0.31178189, 0.79738348, 0.43768332],
       [0.43075754, 0.57020953, 0.58124917, 0.44032735, 0.69852405],
       [0.30667428, 0.40754132, 0.23284713, 0.5956222 , 0.93503386],
       [0.9758611 , 0.62885183, 0.62645655, 0.61911335, 0.09749294],
       [0.84805942, 0.07364064, 0.29943364, 0.23717049, 0.77352702],
       [0.17334416, 0.7111591 , 0.87783796, 0.77523021, 0.65957771]])

In [11]:
x= np.random.normal(5,3,(10,5)) # 평균이 5, 표준 편차가 3
x

array([[ 3.92099569,  8.15089502,  5.7203404 ,  7.70730155,  7.57281074],
       [ 7.14965716,  5.70160018,  0.97461331,  6.19939609,  5.35710163],
       [ 8.31380425,  3.31160977,  9.49105509,  3.50328309,  4.00460351],
       [ 3.60473937,  5.10422884,  2.00686918,  7.69872104,  9.44222383],
       [ 5.20261748,  0.64529448,  4.26282516, -1.9602706 ,  3.05296646],
       [ 2.43583535,  6.57327195,  3.66102784,  2.29731731,  3.75053741],
       [ 0.65940088, 10.23875415,  3.13954224,  6.1276445 ,  6.13392765],
       [ 6.8949013 ,  5.65755276,  0.02952767,  2.47405766,  8.05645612],
       [ 7.20895869,  5.47745516,  2.19647974,  3.1440314 ,  9.20267724],
       [-1.85758425,  7.62316589,  6.43149733,  6.69772237, -2.64172007]])